# Name of the pipeline
name: Version update pipeline

on:
  # When pull request
  pull_request:
    types: [closed]
    branches:
    - main
env:
  NAME_VERSION_FILE: version
# Can be named however we want
# Can have a lot of jobs
jobs: 
  # runs-on: where it run
  # uses: what library it use
  validate-branch:
    runs-on: ubuntu-latest
    steps:
        # action
        # run is necessary
  
        - name: Print info about actions
          id: repo-info
          run: |
            echo "EVENT NAME    : ${{ github.event_name }}"
            echo "ACTION        : ${{ github.event.action }}"
            echo "IS            : ${{ github.event.pull_request.merged }}"
            echo "CURRENT BRANCH: ${{ steps.branch-names.outputs.current_branch }}"
            echo "REF           : ${{ github.ref}}"
            echo "REF NAME      : ${{ github.ref_name}}"
            echo "ACTION        : ${{ github.event.action}}"
            echo "DEFAULT BRANCH: ${{ github.branch-names.outputs.default_branch  }}"
  #
  print-data-information:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: echo "Print info"
      - name: 3 step
        run: echo "Print info"
          
